"""Add content in books model

Revision ID: 9066f8ca07ff
Revises: b881c5efb473
Create Date: 2022-06-21 13:57:11.797929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9066f8ca07ff'
down_revision = 'b881c5efb473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'content')
    # ### end Alembic commands ###
