"""Add type

Revision ID: e8e440f55e82
Revises: 9066f8ca07ff
Create Date: 2022-06-22 21:19:40.187829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e440f55e82'
down_revision = '9066f8ca07ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'type')
    # ### end Alembic commands ###
